### ISSUE TITLE
Add optional ramp parameters

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#102]
To individually speed up ramp up and down actions add optional parameters for instruments, eg. `voltage_step_before` and `voltage_step_after` defaulting to `voltage_step`

```yaml
  ...
  parameters:
    voltage_start: -5 V
    voltage_stop: +5 V
    voltage_step: 1 V
    waiting_time: 1 s
    voltage_step_before: 5 V
    waiting_time_before: 0 ms
    voltage_step_after: 5 V
    waiting_time_after: 0 ms
    waiting_time_start: 1 s
    waiting_time_end: 1 s
```
![ramping](https://user-images.githubusercontent.com/3717588/98926487-ac2b0080-24d7-11eb-9818-44ae2bab7808.png)
