### ISSUE TITLE
Limits for analysis results

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#133]
Add user defined range limits for results of analysis functions, e.g.
```yaml
...
parameters:
  analysis_functions:
    - van_der_pauw:
      limits:
        a: {minimum: -0.5, maximum: +0.5}
        b: {minimum: 1.0, maximum: 2.0}
```
