### ISSUE TITLE
Compliance parameter for initialization

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#153]
Add compliance parameter to overcome high currents at initialization ramps that result in compliance errors.

```yaml
parameters:
    compliance_before: 2.5 mA
    compliance: 100 uA
```
