### ISSUE TITLE
configurable plot axis units

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#20]
Add configuration parameters to configure units for X and Y axis of measurement plots, as range of displayed series depends on type of test structure, eg.

```yaml
parameters:
  plot_axis_x_unit: V
  plot_axis_y_unit: nA
```
