### ISSUE TITLE
Add open correction mode/channel select for LCR

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#24]
Switch LCR open correction mode single/multi and select correction channel for multi mode, eg.

```yaml
parameters:
  lcr_open_correction_mode: multi
  lcr_open_correction_channel: 42
```
