### ISSUE TITLE
Use IDs instead of names in data filenames

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#36]
Contact and measurement names are often to verbose (can include special characters) for use in data filenames. Add configuration key `id` for contacts and measurements to be used for filenames (if available), else a mangled version of the name is used as fallback.

Proposal:
```yaml
measurements:
  - id: rev_nplus_VdP_cross
    name: Reverse N+ Van-der-Pauw cross (V Source)
    ...
```
