### ISSUE TITLE
Analysis functions parameter

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/comet-pqc#82]
Use optional measurement parameter `analysis_functions` (list) to trigger analysis functions for the acquired data.

```yaml
  - name: MOS capacitor (LCR)
    type: cv_ramp_alt
    parameters:
      analysis_functions: [cv, mos]
```
